/* Generated by scripts/gen-themes.mjs — do not edit by hand. */

export interface ThemeInfo {
  id: string;
  label: string;
  kind: "dark" | "light";
}

export const THEME_LIST: readonly ThemeInfo[] = [
  { id: "dark-plus", label: "Dark+", kind: "dark" },
  { id: "dark-modern", label: "Dark Modern", kind: "dark" },
  { id: "monokai", label: "Monokai", kind: "dark" },
  { id: "monokai-dimmed", label: "Monokai Dimmed", kind: "dark" },
  { id: "solarized-dark", label: "Solarized Dark", kind: "dark" },
  { id: "abyss", label: "Abyss", kind: "dark" },
  { id: "kimbie-dark", label: "Kimbie Dark", kind: "dark" },
  { id: "red", label: "Red", kind: "dark" },
  { id: "tomorrow-night-blue", label: "Tomorrow Night Blue", kind: "dark" },
  { id: "hc-black", label: "High Contrast Dark", kind: "dark" },
  { id: "light-plus", label: "Light+", kind: "light" },
  { id: "light-modern", label: "Light Modern", kind: "light" },
  { id: "solarized-light", label: "Solarized Light", kind: "light" },
  { id: "quiet-light", label: "Quiet Light", kind: "light" },
  { id: "hc-light", label: "High Contrast Light", kind: "light" },
];
